apiVersion: v1
kind: Pod
metadata:
  name: whoami
  labels:
    kubernetes.courselabs.co: services
    app: whoami
spec:
  containers:
    - name: app
      image: ubuntu:22.04
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "128Mi"
      
